### ISSUE TITLE
Login failed. Failed to load the list of Task Hubs. Request failed with status code 401

### ISSUE THREAD

**Issue by jmelosegui** [microsoft/DurableFunctionsMonitor#218]
I am unable to get the security working despite going through the documentation multiple times.

I can see the environment variables inside the kubernetes pod.

```
➜ kubectl exec -it $podname --insecure-skip-tls-verify -- bash -c "tr '\0' '\n' < /proc/1/environ | sort | grep DFM"
DFM_ALLOWED_APP_ROLES=DLS-ADMINS,b4ae5da0-6825-4c5a-9c5d-a66e968778c1
DFM_ALLOWED_READ_ONLY_APP_ROLES=DLS-READERS,e3acdf6d-cbf7-46ae-bef5-2cef4bb6d0cf
DFM_INGRESS_ROUTE_PREFIX=global-deployment-monitor
DFM_SERVICE_PORT=tcp://172.20.214.215:80
DFM_SERVICE_PORT_80_TCP=tcp://172.20.214.215:80
DFM_SERVICE_PORT_80_TCP_ADDR=172.20.214.215
DFM_SERVICE_PORT_80_TCP_PORT=80
DFM_SERVICE_PORT_80_TCP_PROTO=tcp
DFM_SERVICE_SERVICE_HOST=172.20.214.215
DFM_SERVICE_SERVICE_PORT=80
```

I even included the role ID (just in case). 

But no matter the configuration, I always get this popup.

![Image](https://github.com/user-attachments/assets/70cf3b73-f7ef-4f72-b1d8-70bd76973e2e)

If I remove `DFM_ALLOWED_APP_ROLES` and `DFM_ALLOWED_READ_ONLY_APP_ROLES` then I can login properly, but I cannot control who can login to the monitor.

What am I missing?

Thanks in advance

**Comment by scale-tone** [comment]
@jmelosegui , since you said you can login, I'm assuming `WEBSITE_AUTH_CLIENT_ID` and `WEBSITE_AUTH_OPENID_ISSUER` settings are configured correctly (and they just don't appear in your env var dump for whatever reason).

Do you see that role (those roles) in your JWT token (should appear in `roles` claim)?

If yes, then it might mean that in your setup this claim appears in the ClaimsPrincipal object under a different, non-default name ([a typical gotcha](https://stackoverflow.com/questions/41162255/azure-aad-role-based-authentication-user-isinrole)).

To accomodate for that we have `DFM_ROLES_CLAIM_NAME` setting. Can you try to set it to e.g. `http://schemas.microsoft.com/ws/2008/06/identity/claims/role` and see if it helps?

**Comment by jmelosegui** [comment]
Hi @scale-tone ,

That is exactly right!

Yesterday I cloned this repo and, upon running the code, I realized that the `roleClaim` name is in fact what you mentioned:
```
DFM_ROLES_CLAIM_NAME=http://schemas.microsoft.com/ws/2008/06/identity/claims/role
```
After setting that variable, everything worked as expected.

Apologies for not getting back sooner, and thank you for taking the time to clarify!
