### ISSUE TITLE
[Standalone Service] [6.0] "Your app is pinned to an unsupported runtime version"

### ISSUE THREAD

**Issue by czart8** [microsoft/DurableFunctionsMonitor#74]
Standalone version missing specified "netFrameworkVersion": "v6.0", so in azure app configuration warning is displayed:
"Your app is pinned to an unsupported runtime version for 'xxx'. For better performance, we recommend using one of our supported versions instead: xxx."

**Comment by scale-tone** [comment]
@czart8 , can you clarify how exactly you deployed your DfMon instance?

Have you used the provided ARM template aka the blue `Deploy to Azure` button? Because if you did, then the ARM template [does currently have that line included](https://github.com/microsoft/DurableFunctionsMonitor/blob/main/durablefunctionsmonitor.dotnetbackend/arm-template.json#L101), so you shouldn't be seeing that warning.

**Comment by czart8** [comment]
> @czart8 , can you clarify how exactly you deployed your DfMon instance?
> 
> Have you used the provided ARM template aka the blue `Deploy to Azure` button? Because if you did, then the ARM template [does currently have that line included](https://github.com/microsoft/DurableFunctionsMonitor/blob/main/durablefunctionsmonitor.dotnetbackend/arm-template.json#L101), so you shouldn't be seeing that warning.

I'm sorry, my bad. We've deployed monitor by a Terraform and didn't specify  this value.
